"""Dirección de grupo ICET 2026 (PDF 'DIRECCIÓN DE GRUPO', publicaciones 3 y 10 de marzo de 2026).

Cada entrada: código de grupo -> (nombre en el PDF, n.º en la lista oficial del Word)... de uno o dos docentes.
En bachillerato la dirección es dual: ambos son responsables (no hay titular ni suplente).
"""
# Preescolar y primaria: un(a) dinamizador(a) por grupo. modalidad = columna "Extra edad" del PDF.
BASICA_PDF = {
    "0001": ("GLORIA ALEXA VALENCIA SOLÍS", 50, "PREESCOLAR", ""),
    "0002": ("ANDREA CONCEPCIÓN MARTÍNEZ ÁLVAREZ", 27, "PREESCOLAR", ""),
    "0101": ("MARÍA ELIA LANDÁZURY QUIÑONES", 23, "PRIMARIA", ""),
    "0102": ("ANA LUCÍA SINISTERRA", 45, "PRIMARIA", ""),
    "0201": ("MARÍA EBELICE CORTÉS SALAZAR", 13, "PRIMARIA", ""),
    "0202": ("SIXTA JANINA GARZÓN QUIÑONES", 21, "PRIMARIA", ""),
    "0203": ("LUCY BIVIAN TENORIO CUERO", 46, "PRIMARIA", ""),
    "0301": ("ENCARNACIÓN TORRES SEGURA", 48, "PRIMARIA", ""),
    "0302": ("TERESA LANDÁZURY GALLÓN", 24, "PRIMARIA", "PROCESOS BÁSICOS"),
    "0401": ("CELIA PASTORA ZAMORA ORDÓÑEZ", 55, "PRIMARIA", ""),
    "0402": ("ELCY NÚÑEZ PERLAZA", 33, "PRIMARIA", ""),
    "0501": ("NEMECIA CUÉLLAR GALLO", 14, "PRIMARIA", ""),
    "0502": ("CLAUDIA PATRICIA CENTENO ZÚÑIGA", 11, "PRIMARIA", ""),
    # El PDF de marzo dice 5°-3 Escobar y 5°-4 Narváez; el coordinador confirmó (oct-2026) lo contrario, igual que sus registros.
    "0503": ("DORA ALEJANDRA NARVÁEZ SÁNCHEZ", 32, "PRIMARIA", "ACELERACIÓN DEL APRENDIZAJE"),
    "0504": ("LILIANA ESCOBAR CORTÉS", 17, "PRIMARIA", "ACELERACIÓN DEL APRENDIZAJE"),
}

# Bachillerato: (docente 1, n.º), (docente 2, n.º)
BACHILLERATO_PDF = {
    "0601": (("MARCOS VIDAL QUIÑONES CABEZAS", 42), ("HÉCTOR FABIO MONTAÑO ANCHICO", 30)),
    "0602": (("AMANDA INÉS LOZANO TORRES", 26), ("JESÚS ARMERO DÁJOME", 57)),
    "CS101": (("SAIDY MAGALY GARCÍA GOVEA", 20), ("HERNANDO JESÚS CUERO RINCÓN", 16)),
    "CS102": (("ANA MILENA PUCHES", 39), ("SEGUNDO LEONCIO VÁSQUEZ VALENCIA", 52)),
    "0701": (("DAIRA ENEIDA CASTILLO CUERO", 10), ("JAIME MARCIAL ORDÓÑEZ TENORIO", 34)),
    "0702": (("MARÍA DEL CARMEN QUINTERO RAMÍREZ", 41), ("GENÍS MARIBEL PRADO QUIÑONES", 37)),
    "0703": (("MARTHA CECILIA CASTILLO ANGULO", 9), ("JORGE ANDRÉS AGUIRRE RIASCOS", 1)),
    "0704": (("ROBERTO CARLOS ARIZALA CASTRO", 4), ("JIMMY EDUARDO RAMÍREZ GUERRA", 43)),
    "0801": (("MARÍA TERESA VALVERDE MONTAÑO", 51), ("ALFREDO ENRIQUE FERNÁNDEZ VÉLEZ", 19)),
    "0802": (("MARÍA ROCÍO CHILLAMBO QUIÑONES", 12), ("YOLI DEL CARMEN CASANOVA QUIÑONES", 8)),
    "CS201": (("OLEISA PRECIADO TORRES", 38), ("ADIELA CARLOTA ORTIZ ARAUJO", 35)),
    "CS202": (("FLOR MIREYA SAMANIEGO ANGULO", 44), ("BERTE LEVI CUERO BAMBA", 15)),
    "0901": (("ROSARIO ESTACIO ESTUPIÑÁN", 18), ("JÓLMER JIMY GONZÁLEZ CASTILLO", 22)),
    "0902": (("SENEIDA JUDITH BASTIDAS VALENCIA", 5), ("HÉCTOR HUGO VILLOTA RUBIO", 53)),
    "1001": (("GLADYS ALICIA MEZA BANGUERA", 28), ("JOHN JÁVER MINDINEROS SATIZÁBAL", 29)),
    "1002": (("JANETH DEL CARMEN VILLOTA RUBIO", 54), ("YOHANA PATRICIA BETANCOURTH OCAMPO", 6)),
    "1101": (("ANDRÉS MAURICIO ANGULO LUCERO", 2), ("SAIDY EUFEMIA VALENCIA MARÍNEZ", 49)),
    "1102": (("LUZ AMÉRICA ARBOLEDA ORTIZ", 3), ("LEIDIS CLAUDINA MONTAÑO ARIZALA", 31)),
}
# Sin dirección de grupo (se asignarán si se crea un grupo nuevo): Miriam Lemos Guancha (25), César Marino Pulgarín Ortiz (40)
SIN_DIRECCION = {25, 40}
